ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

NUM_ENVIRONMENTS: 1
ENV_NAME: SinglecamRLEnv-v0
EXP_NAME: test-exp-singlecam-bounce
TRAINER_NAME: bouncebaseline
NUM_UPDATES: -1
TOTAL_NUM_STEPS: 1000
NUM_CHECKPOINTS: 100
CHECKPOINT_INTERVAL: -1

# Can be uncommented to generate videos.
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "tb_bounce"
VIDEO_DIR: "video_dir_bounce"


SIMULATOR:
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR", "SEMANTIC_SENSOR"]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True 
  RGB_SENSOR:
    WIDTH: 512
    HEIGHT: 512
  DEPTH_SENSOR:
    WIDTH: 512
    HEIGHT: 512
    NORMALIZE_DEPTH: False
  SEMANTIC_SENSOR:
    WIDTH: 512
    HEIGHT: 512  
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'OBJECT_DETECTOR_GT_SENSOR', 'AGENT_POSITION_SENSOR', 'GT_EGO_MAP', 'OBJECT_DETECTOR',"AGENT_COLLISION_SENSOR"]

  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  OBJECT_DETECTOR:
    TYPE: object_detector_detectron
  OBJECT_DETECTOR_GT_SENSOR:
    TYPE: object_detector_gt
  AGENT_POSITION_SENSOR:
    TYPE: position_sensor
  GT_EGO_MAP:
    MAP_SIZE: 101
    MAP_SCALE: 0.05
    MAX_SENSOR_RANGE: 3.25
    HEIGHT_THRESH: [0.2, 1.5]
    MAP_SIZE: 101
    MAP_SCALE: 0.05
    HEIGHT_THRESH: [0.2, 1.5]
    MAX_SENSOR_RANGE: 5.05
    NUM_TOPDOWN_MAP_SAMPLE_POINTS: 20000
    TYPE: gt_ego_map
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  OBJECT_DETECTOR:
    TYPE: object_detector_detectron
  AGENT_COLLISION_SENSOR:
    TYPE: agent_collision_sensor
        
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'TOP_DOWN_MAP']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
RL:
  SUCCESS_REWARD: 2.5
DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz
  
FILTER: []
