defaults:
  - detectron_args: maskrcnn
  - replay: rgb_depth_multicam  

base_dir: /path/to/project/data
habitat_base_cfg_dir: ${base_dir}/confs/habitat
habitat_cfg: gibson_randomgoals.yaml

exp_base_dir: /data/exps
data_base_dir: ${base_dir}/data
