defaults:
  - detectron_args: maskrcnn
  - replay: rgb_depth_multicam
  - training: pipeline_ce

base_dir: /path/to/project/data

habitat_base_cfg_dir: ${base_dir}/confs/habitat
habitat_cfg: gibson_goal_exploration.yaml
exp_base_dir: ${base_dir}/exps
data_base_dir: ${base_dir}/data
early_stopping: 0
epochs: 20
gpus: 1

notes: 
exp_name: ${now:%m-%d-%H-%M-%S}_habitat_${habitat_cfg}_${training.exp_name_training}_consensus_${training.consensus}_batchsize_${training.batch_size}_${training.lr}_contrastive_${training.loss_weights.contrastive_loss}_notes_${notes}

test_set: fix_test #test_scene_test

hydra:
  output_subdir: reproduce
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '_'
        item_sep: '__'
        exclude_keys: []
  sweep:
    dir: ${exp_base_dir}/${training.exp_base_name}
    subdir: ${exp_name}
    
  run:
    dir: ${hydra.sweep.dir}/${hydra.sweep.subdir}
      
